# Generated by Django 4.1 on 2025-03-16 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('high_score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureGameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('questions_left', models.IntegerField(default=5)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('game_status', models.CharField(choices=[('active,', 'Active'), ('completed', 'Completed')], default='active', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.player')),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('user_guess', models.FloatField()),
                ('actual_temperature', models.FloatField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_limit', models.IntegerField(default=30)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='games.temperaturegamesession')),
            ],
        ),
    ]
