# Generated by Django 5.1.6 on 2025-03-14 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('questions_left', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('user_guess', models.FloatField(blank=True, null=True)),
                ('actual_temparature', models.FloatField()),
                ('time_limit', models.IntegerField(default=30)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='games.temperaturegame')),
            ],
        ),
    ]
