# Generated by Django 5.1.6 on 2025-03-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperaturegamesession',
            old_name='user',
            new_name='player',
        ),
        migrations.AlterField(
            model_name='temperaturegamesession',
            name='game_status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=10),
        ),
    ]
