# Generated by Django 4.2.20 on 2025-04-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_user_temperaturegamesession_player_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperaturegamesession',
            old_name='total_score',
            new_name='score',
        ),
    ]
