# Generated by Django 5.1.6 on 2025-04-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_user_temperaturegamesession_player_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperaturegamesession',
            old_name='total_score',
            new_name='score',
        ),
        migrations.AlterField(
            model_name='temperaturequestion',
            name='user_guess',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
