# Generated by Django 4.2.20 on 2025-04-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_rename_total_score_temperaturegamesession_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturequestion',
            name='user_guess',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
