# Generated by Django 4.2.20 on 2025-04-19 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_triviaquestion_weatherleaderboard_trivialeaderboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviaquestion',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='triviaquestion',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
        migrations.AddField(
            model_name='triviaquestion',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='games.triviagamesession'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triviaquestion',
            name='incorrect_answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triviaquestion',
            name='question_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triviaquestion',
            name='question_type',
            field=models.CharField(blank=True, choices=[('multiple', 'Multiple Choice'), ('boolean', 'Boolean')], max_length=10, null=True),
        ),
    ]
