# Generated by Django 4.2.20 on 2025-04-19 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_triviaquestion_correct_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triviaquestion',
            name='game',
        ),
    ]
