# Generated by Django 4.2.20 on 2025-04-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_remove_triviaquestion_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherleaderboard',
            name='player',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='high_score',
            new_name='trivia_high_score',
        ),
        migrations.RemoveField(
            model_name='temperaturegamesession',
            name='time_created',
        ),
        migrations.RemoveField(
            model_name='temperaturequestion',
            name='time_created',
        ),
        migrations.RemoveField(
            model_name='temperaturequestion',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='player',
            name='weather_high_score',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='TriviaLeaderBoard',
        ),
        migrations.DeleteModel(
            name='WeatherLeaderBoard',
        ),
    ]
