# Generated by Django 4.2.20 on 2025-04-26 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_rename_total_score_temperaturegamesession_score_and_more'),
        ('games', '0008_remove_weatherleaderboard_player_and_more'),
    ]

    operations = [
    ]
