name: tester
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django djangorestframework pytest pytest-django
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Check file structure
        run: |
          ls -la guessquest/guessquest/
          ls -la guessquest/games/
          
      - name: Create symbolic link or adjust imports
        run: |
          cd guessquest/games
          ln -sf ../guessquest/trivia_service.py trivia_service.py
          
      - name: Run Django tests
        run: |
          cd guessquest
          python manage.py test games
